import { defineConfig } from "oxlint";
export default defineConfig({
  ignorePatterns: [
    "**/node_modules/**",
    "**/.next/**",
    "**/.turbo/**",
    "**/.data/**",
    "**/coverage/**",
    "apps/web/public/pdf.worker.min.mjs",
    "tools/oxlint/anti-slop/**",
    ".agents/**",
    ".codex/**",
  ],
  plugins: ["typescript", "react", "jsx-a11y", "nextjs"],
  jsPlugins: [
    { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
    { name: "anti-slop-effect", specifier: "./tools/oxlint/anti-slop/effect/index.ts" },
  ],
  rules: {
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-runtime-typeof": "error",
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
    "anti-slop-effect/no-service-constructor-imports": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-non-null-assertion": "error",
    "react/rules-of-hooks": "error",
    "react/exhaustive-deps": "error",
  },
});
